# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup-server:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: project-int493
      DISK_NAME: lab1-vm_DataDisk_0
      VM_SIZE: Standard_B1s
      VM_NAME: lab1-vm
      VM_IMAGE: Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202101191

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Delete VM
      run: |
        az vm delete \
          --resource-group $RESOURCE_GROUP \
          --name $VM_NAME -y
    - name: Delete Disk
      run: |
        az disk delete \
          --name $DISK_NAME \
          --resource-group $RESOURCE_GROUP -y
    - name: Create Disk
      run: |
        az disk create \
          --name $DISK_NAME \
          --resource-group $RESOURCE_GROUP \
          --size-gb 8
    - name: Create VM
      run: |
        az vm create \
          --resource-group $RESOURCE_GROUP \
          --name $VM_NAME \
          --image $VM_IMAGE \
          --admin-username ${{ secrets.SSH_USER }} \
          --admin-password ${{ secrets.SSH_PASSWORD }} \
          --attach-data-disks $DISK_NAME \
          --size $VM_SIZE
    - name: Open Port
        az vm open-port \
          --port 8080
          --name $VM_NAME
          --priority 1010
          --resource-group $RESOURCE_GROUP
    - name: Delete DNS record set
      run: |
        az network dns record-set a delete \
          --name @ \
          --resource-group $RESOURCE_GROUP \
          --zone-name ${{ secrets.HOSTNAME }} -y
    - name: Create a new DNS record
      run: |
        IP=$(az vm show -d -g $RESOURCE_GROUP -n $VM_NAME --query publicIps -o tsv)
        az network dns record-set a create \
          --name @ \
          --resource-group $RESOURCE_GROUP \
          --zone-name ${{ secrets.HOSTNAME }} -o none
        az network dns record-set a add-record --ipv4-address $IP \
          --record-set-name @ \
          --resource-group $RESOURCE_GROUP \
          --zone-name ${{ secrets.HOSTNAME }} \
          --ttl 300 -o none

  deploy-application:
    runs-on: ubuntu-latest
    needs: [ setup-server ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy package to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "target/demo-0.0.1-SNAPSHOT.jar,myapp.service"
        target: "."
    - name: Start Application with Linux Service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          sudo apt install default-jre -y
          sudo mv myapp.service /etc/systemd/system/myapp.service
          sudo systemctl enable myapp.service
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
