# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup-server:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Delete VM
      run: |
        az vm delete -g group-project -n lab1-vm --yes
    - name: Delete Disk
      run: |
        az disk delete --name lab1-vm_DataDisk_0 --resource-group group-project
    - name: Delete Resource Group
      run: |
        az group delete -n group-project
    - name: Create Resource Group
      run: |
        az group create --name group-project \
          --location southeastasia
    - name: Create Disk
      run: |
        az disk create --name lab1-vm_DataDisk_0 \
          --resource-group group-project \
          --size-gb 8
    - name: Create VM
      run: |
        az vm create \
            --resource-group group-project \
            --name lab1-vm \
            --image Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202101191 \
            --admin-username ${{secrets.SSH_USER}} \
            --admin-password ${{secrets.SSH_PASSWORD}} \
            --attach-data-disks lab1-vm_DataDisk_0 \
            --size Standard_B1s

  deploy-application:
    runs-on: ubuntu-latest
    needs: [setup-server]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "target/demo-0.0.1-SNAPSHOT.jar"
          target: "."
      - name: Start app via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            mv target/*.jar web-api.jar
            kill $(pidof java)
            java -jar web-api.jar > app.log 2>&1 </dev/null &
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
