# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup-server:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Resource Group
      run: |
        az group create --name group-project \
          --location southeastasia
    - name: Create disk
      run: |
        az disk create --name lab1-vm_DataDisk_0 \
          --resource-group group-project \
          --size-gb 8
    - name: Create VM
      run: |
        az vm create \
            --resource-group group-project \
            --name lab1-vm \
            --image Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202101191 \
            --admin-username ${{secrets.SSH_USER}} \
            --admin-password ${{secrets.SSH_PASSWORD}} \
            --attach-data-disks lab1-vm_DataDisk_0 \
            --size Standard_B1s
    - name: Open Port
      run: |
        az vm open-port -g group-project -n lab1-vm --port '22'