# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate the package
        run: mvn -B package --file pom.xml
      - name: Deploy the package to the remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "target/demo-0.0.1-SNAPSHOT.jar"
          target: "./"
      - name: Start Application
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd target/ && nohup java -jar demo-0.0.1-SNAPSHOT.jar > /dev/null &
            host: ${{ secrets.HOST }}
            user: ${{ secrets.SSH_USER }}
            pass: ${{ secrets.SSH_PASSWORD }}
            args: "-tt"